server {
    listen 80;
    server_name localhost;

    # Корневая директория, где лежат файлы проекта
    root /var/www/html;
    index index.php index.html;

    # Логи внутри контейнера
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # 1. Сначала пробуем отдать файл напрямую ($uri).
    # Если это папка — смотрим ($uri/).
    # Если ничего не найдено — отправляем запрос на index.php с параметрами (роутинг MVC)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # 2. Обработка всех .php файлов через FastCGI в соседний контейнер
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # 'php' — это имя сервиса из docker-compose, порт по умолчанию 9000
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        
        include fastcgi_params;
        # Передаем путь к скрипту, чтобы PHP-FPM знал, какой файл запускать
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # 3. Защита служебных скрытых файлов (например, .htaccess или .git)
    location ~ /\.ht {
        deny all;
    }
}